/**
 * Configuration constants for the network canvas animations.
 * @author Adam Ross DeStafeno
 * @version 1.2.0
 */
export const NetworkConfig = {
  // Background Config
  AMBIENT_NODE_RATIO: 15000,
  STRAND_NODE_RATIO: 2000,
  MAX_DIST_CONSTELLATION: 25000,
  MAX_DIST_CIRCUIT: 25000,
  CONSTELLATION_HUE_MIN: 190,
  CONSTELLATION_HUE_VAR: 25,
  CIRCUIT_HUE_MIN: 165,
  CIRCUIT_HUE_VAR: 30,
  PULSE_LIMIT: 80,
  GRID_SNAP: 10,
  CROSS_LINK_CHANCE: 0.5,
  CROSS_LINK_MIN_DIST_SQ: 100,
  CROSS_LINK_MAX_DIST_SQ: 8100,
  HERD_MENTALITY_DIST_SQ: 3600,
  FLOW_CURVE_CHANCE: 0.8,

  // Header Config
  PARTICLE_COUNT: 80,
  TRAIL_LENGTH: 12,
  NODE_COUNT: 70,
  MAX_PARTICLE_DIST_SQ: 12000,
  MAX_NODE_DIST_SQ: 5000,
  CORE_SCALE_BASE: 250,
  CORE_SCALE_DIV: 80,
  CORE_RADIUS_MULT: 120,
};
