name: Update Visual Snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # Add the secret to the job's environment to bypass local linter errors
    env:
      GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true
          ref: ${{ github.head_ref || github.ref }}
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run build
      - name: Update Snapshots
        run: npx playwright test --update-snapshots

      - name: Import GPG Key for Verified Signatures
        uses: crazy-max/ghaction-import-gpg@v6
        if: env.GPG_KEY != ''
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: false

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'test(visuals): update playwright baseline snapshots'
          file_pattern: '**/*.png'
          commit_user_name: 'Ryuukae'
          commit_user_email: 'ryuukae.dev@gmail.com'
          commit_author: 'Ryuukae <ryuukae.dev@gmail.com>'
